# Generated by Django 4.0.4 on 2022-05-01 10:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literature', models.URLField(blank=True, max_length=1000, unique=True)),
                ('literature_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('department', models.CharField(blank=True, max_length=300, null=True)),
                ('discipline', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(blank=True, max_length=300, null=True)),
                ('literature_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.literaturetable')),
            ],
        ),
        migrations.AddField(
            model_name='literaturetable',
            name='input_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.logintable'),
        ),
    ]
